"""Optionally render synthetic scripts with an installed, offline pyttsx3 voice.

Rendering is intentionally opt-in. The source scripts are complete without a
TTS dependency; this command never uses a cloud service or customer material.
"""

from __future__ import annotations

import argparse
import json
import wave
from pathlib import Path


def _load_scripts(path: Path) -> list[dict]:
    scripts = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if len(scripts) != 20:
        raise ValueError(f"Expected 20 complete scripts, found {len(scripts)}")
    for script in scripts:
        if not script.get("turns") or any(not turn.get("text") or turn.get("speaker") not in ("customer", "assistant") for turn in script["turns"]):
            raise ValueError(f"Incomplete script: {script.get('script_id')}")
    return scripts


def render(source: Path, output: Path, max_characters: int, dry_run: bool) -> dict:
    scripts = _load_scripts(source)
    characters = sum(len(turn["text"]) for script in scripts for turn in script["turns"])
    if characters > max_characters:
        raise ValueError(f"Script corpus has {characters} characters, above the explicit {max_characters} character budget")
    manifest = {"source": str(source), "provenance": "Synthetic scripts generated by scripts/generate_scenarios.py; no real caller audio", "provider": "pyttsx3-offline", "cloud_cost_usd": 0, "scripts": len(scripts), "utterances": sum(len(script["turns"]) for script in scripts), "characters": characters, "status": "dry_run" if dry_run else "rendered", "files": []}
    if dry_run:
        return manifest
    try:
        import pyttsx3  # type: ignore[import-not-found]
    except ImportError as exc:
        raise RuntimeError("Offline TTS is unavailable. Install pyttsx3 in a local environment, or keep the 20 complete scripts marked audio pending.") from exc
    engine = pyttsx3.init()
    voices = engine.getProperty("voices") or []
    if not voices:
        raise RuntimeError("No local TTS voice is installed; audio fixtures remain pending")
    engine.setProperty("rate", 165)
    output.mkdir(parents=True, exist_ok=True)
    for script in scripts:
        script_dir = output / script["script_id"]
        script_dir.mkdir(parents=True, exist_ok=True)
        for index, turn in enumerate(script["turns"], 1):
            voice = voices[0] if turn["speaker"] == "customer" or len(voices) == 1 else voices[1]
            engine.setProperty("voice", voice.id)
            wav_path = script_dir / f"{index:02d}-{turn['speaker']}.wav"
            engine.save_to_file(turn["text"], str(wav_path))
            engine.runAndWait()
            if not wav_path.exists() or wav_path.stat().st_size == 0:
                raise RuntimeError(f"Offline TTS did not produce {wav_path}")
            with wave.open(str(wav_path), "rb") as audio:
                if audio.getnframes() == 0:
                    raise RuntimeError(f"Empty WAV frames: {wav_path}")
            manifest["files"].append({"script_id": script["script_id"], "turn": index, "speaker": turn["speaker"], "path": str(wav_path), "voice_id": voice.id})
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path("fixtures/audio_scripts/scripts.jsonl"))
    parser.add_argument("--output", type=Path, default=Path("fixtures/generated/audio"))
    parser.add_argument("--max-characters", type=int, default=50_000)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    result = render(args.source, args.output, args.max_characters, args.dry_run)
    print(json.dumps({key: result[key] for key in ("scripts", "utterances", "characters", "cloud_cost_usd", "status")}))


if __name__ == "__main__":
    main()
